name: B4A Auto Redeploy

on:
  #repository_dispatch:
  #  types: [googlecloud-trigger]   # 必须和 event_type 完全一致
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # =========================
      # 🟡 ⭐ 私有仓库
      # =========================
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/Back4app
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install seleniumbase requests pynacl

      - name: Run redeploy script
        env:
          CONNECT_SID: ${{ secrets.CONNECT_SID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python b4a_redeploy.py

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
